### ISSUE TITLE
Mavic mini 1 seems to do not have geolocalization data in exif...

### ISSUE THREAD

**Issue by RomainB91** [Theta-Limited/OpenAthenaAndroid#67]
Hi,

Thanks a lot for OpenAthena for Android !

I cannot work with Open Athena for Android and my mavic mini 1.

I do not understand : It seems that my Mavic mini 1 seems to do not have geolocalization data in exif under irfanview.
But when i look at the pic in my android phone... it show me some geolocalization data in google map !

Please could you help me, i do not understand.

**Comment by mkrupczak3** [comment]
Hi @RomainB91, 

Are you having trouble using with OpenAthena for Android with your drone images? If so, feel free to send some in an email ([matthew.krupczak@theta.limited](mailto:matthew.krupczak@theta.limited)) and I'd be happy to take a look.

In general, photo metadata for drone images is either stored in either [EXIF](https://exiftool.org/TagNames/EXIF.html) metadata, Adobe [XMP](https://exiftool.org/TagNames/XMP.html) metadata, or both. If you send images via a messaging app or social media, this data (especially location tags) is sometimes automatically removed to protect user privacy. This may explain why you can see the location data on your phone but not on your computer. You can use a free tool called [ExifTool](https://exiftool.org/) to check if the data has been removed or zeroed out after your transfer.

Your Mavic Mini 1 has camera model `FC7203`. I've tried a [few images from online](https://commons.wikimedia.org/wiki/Category:Taken_with_DJI_FC7203), and believe you could expect the following:

<img width="512" alt="Screenshot 2023-05-04 at 10 27 15 AM" src="https://user-images.githubusercontent.com/25494111/236237884-9bbf4b9f-3fe6-4093-92b6-0152014c8e37.png">

Latitude, Longitude, and Altitude will be present in the EXIF tags, but not XMP tags. Camera gimbal yaw and pitch are stored within XMP tags. This should be sufficient to work with OpenAthena.

Some older DJI drones incorrectly use their relative altitude from their start point as their "absolute altitude". If so, the data will be incompatible with OpenAthena. Sometimes this can be fixed with a firmware update, but this is not guaranteed.

If the data has been removed by your messaging app or other software, the Exif.GPSInfo tags will be zeroed out like this:

<img width="512" alt="Screenshot 2023-05-04 at 10 39 50 AM" src="https://user-images.githubusercontent.com/25494111/236241958-0d071ff8-cf00-45b5-acf1-d454ddfb75b0.png">

**Comment by mkrupczak3** [comment]
I'm keeping this issue open until I can do more testing with the Mavic Mini

**Comment by RomainB91** [comment]
Hi, thanks a lot.

If i could help you providing more pictures from the mini (i have a lot of
new ones :-)) or anything else, do not hesitate to ask me.

Best regards,


Romain

**Comment by mkrupczak3** [comment]
Hi @RomainB91,

Wanted to let you know that v0.16.0 is out, with vastly improved accuracy

This may reduce some of the problems you encountered earlier

**Comment by RomainB91** [comment]
Hi,


Thanks for the update :)

Have a nice weekend !


Best regards,



Romain

Le sam. 10 juin 2023 à 18:03, mkrupczak3 ***@***.***> a
écrit :
